# Generated by Django 2.0.2 on 2018-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20180403_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationresponse',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
