# Generated by Django 2.0.2 on 2018-04-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0009_auto_20180412_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aliasname',
            field=models.CharField(default='none', max_length=12, unique=True),
        ),
    ]
