# Generated by Django 2.0.2 on 2018-04-03 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateResponse',
            fields=[
                ('idaffiliate', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppProperty',
            fields=[
                ('idappproperty', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CountResponse',
            fields=[
                ('idcount', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationResponse',
            fields=[
                ('ideducation', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=24)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalHealthResponse',
            fields=[
                ('idemotionalhealth', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EthnicityResponse',
            fields=[
                ('idethnicity', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=24)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderResponse',
            fields=[
                ('idgender', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=24)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourRangeResponse',
            fields=[
                ('idhourrange', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingResponse',
            fields=[
                ('idhousing', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageResponse',
            fields=[
                ('idlanguage', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0, null=True)),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
        migrations.CreateModel(
            name='NumberRangeResponse',
            fields=[
                ('idrange', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0, null=True)),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idperson', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=24)),
                ('lastname', models.CharField(max_length=24)),
                ('aliasname', models.CharField(default='none', max_length=8)),
                ('aliaspin', models.CharField(default='none', max_length=4)),
                ('shortssn', models.CharField(default='none', max_length=4)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, default='7045550000', max_length=10, validators=[django.core.validators.RegexValidator(message='Area code and number', regex='^\\d{3}-\\d{3}-\\d{4}$|^\\d{10}$|^\\d{3} \\d{3} \\d{4}$')])),
                ('email', models.CharField(blank=True, default='you@somewhere.com', max_length=32, validators=[django.core.validators.RegexValidator(message='name@domain.com', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')])),
                ('streetAddress', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=16)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('timelineStartDate', models.DateField(auto_now=True)),
                ('daysStableHousing', models.IntegerField(default=0)),
                ('daysUnstableHousing', models.IntegerField(default=0)),
                ('daysSheltered', models.IntegerField(default=0)),
                ('daysUnsheltered', models.IntegerField(default=0)),
                ('daysIncarcerated', models.IntegerField(default=0)),
                ('numberMedicalEmergencies', models.IntegerField(default=0)),
                ('numberLawEnforcementEvents', models.IntegerField(default=0)),
                ('numberEducAndReligiousEvents', models.IntegerField(default=0)),
                ('affiliation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guestbook.AffiliateResponse')),
            ],
        ),
        migrations.CreateModel(
            name='PersonNote',
            fields=[
                ('idpersonnote', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonServiceRequest',
            fields=[
                ('idservice', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(db_column='status', null=True)),
            ],
            options={
                'ordering': ('connection__timestamp', 'idservice'),
            },
        ),
        migrations.CreateModel(
            name='PersonSnapshot',
            fields=[
                ('idsnapshot', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('status', models.IntegerField(db_column='status', null=True)),
                ('isSurveyComplete', models.BooleanField(default=False)),
                ('promptsPresented', models.IntegerField(default=0)),
                ('isArchived', models.BooleanField(default=False)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSurvey',
            fields=[
                ('idpersonsurvey', models.BigAutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=64, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.PersonSnapshot')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_type_timelines', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('connection__timestamp', 'idpersonsurvey'),
            },
        ),
        migrations.CreateModel(
            name='PhysicalHealthResponse',
            fields=[
                ('idphysicalhealth', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('points', models.IntegerField(default=0, null=True)),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('idprompt', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.NullBooleanField()),
                ('onscreenPrompt', models.CharField(max_length=128)),
                ('intervalDays', models.IntegerField(default=0)),
                ('anchorField', models.CharField(blank=True, max_length=64, null=True)),
                ('responseType', models.CharField(blank=True, max_length=64, null=True)),
                ('regexValidator', models.CharField(blank=True, max_length=128, null=True)),
                ('fencingResponse', models.CharField(blank=True, max_length=64, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('fencingPrompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.Prompt')),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
            options={
                'ordering': ('-priority', 'idprompt'),
            },
        ),
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('idrating', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0, null=True)),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
        migrations.CreateModel(
            name='RoleResponse',
            fields=[
                ('idrole', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=24)),
                ('points', models.IntegerField(default=0, null=True)),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idservice', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('isDiscretionary', models.BooleanField(default=False)),
                ('SUN', models.BooleanField(default=False)),
                ('MON', models.BooleanField(default=True)),
                ('TUE', models.BooleanField(default=True)),
                ('WED', models.BooleanField(default=True)),
                ('THU', models.BooleanField(default=True)),
                ('FRI', models.BooleanField(default=True)),
                ('SAT', models.BooleanField(default=False)),
                ('targetRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.RoleResponse')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsExperienceResponse',
            fields=[
                ('idSkillsExperience', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('points', models.IntegerField(default=0, null=True)),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoResponse',
            fields=[
                ('idyesno', models.BigAutoField(primary_key=True, serialize=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=16)),
                ('points', models.IntegerField(default=0, null=True)),
                ('language', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='targetRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.RoleResponse'),
        ),
        migrations.AddField(
            model_name='personsurvey',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.Prompt'),
        ),
        migrations.AddField(
            model_name='personservicerequest',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.PersonSnapshot'),
        ),
        migrations.AddField(
            model_name='personservicerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.Service'),
        ),
        migrations.AddField(
            model_name='person',
            name='canText',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_cansmstext', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.EducationResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='emotionalHealth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guestbook.EmotionalHealthResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='ethnicity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guestbook.EthnicityResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guestbook.GenderResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='grossIncomeAllSources',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nrange_grossincomeallsources', to='guestbook.NumberRangeResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='grossIncomeChildSupport',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nrange_childsupportincome', to='guestbook.NumberRangeResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='grossIncomeEmployment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nrange_grossemploymentincome', to='guestbook.NumberRangeResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='grossIncomeOther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nrange_otherincome', to='guestbook.NumberRangeResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='grossIncomeOtherRetirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nrange_ssorotherretirementincome', to='guestbook.NumberRangeResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='grossIncomeSsiorDisability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nrange_grossssiordisabilityincome', to='guestbook.NumberRangeResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='housing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guestbook.HousingResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='incidentEmergencyMedical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_incidentemergencymedical', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='incidentLawEnforcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_incidentlawenforcement', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='lastHoursWorked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrange_lasthoursworked', to='guestbook.HourRangeResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='physicalHealth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guestbook.PhysicalHealthResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='receivesChildSupportIncome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_receiveschildsupport', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='receivesEmploymentIncome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_receivesemployment', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='receivesOtherRetirementIncome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_receivesotherretirement', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='receivesSSiOrDisabilityIncome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_receivesssi', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='registeredSexOffender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_isregisteredsexoffender', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.RoleResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='guestbook.SkillsExperienceResponse'),
        ),
        migrations.AddField(
            model_name='person',
            name='veteran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='yesno_isveteran', to='guestbook.YesNoResponse'),
        ),
        migrations.AddField(
            model_name='housingresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='hourrangeresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='genderresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='ethnicityresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='emotionalhealthresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='educationresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='countresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
        migrations.AddField(
            model_name='affiliateresponse',
            name='language',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse'),
        ),
    ]
