# Generated by Django 2.0.2 on 2018-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='onscreenPrompt',
            field=models.CharField(max_length=256),
        ),
    ]
