# Generated by Django 2.0.2 on 2018-04-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_auto_20180404_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('idpreference', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('maxPrompts', models.PositiveIntegerField(default=2)),
                ('snapshotTimeout', models.PositiveIntegerField(default=0)),
                ('timewarp', models.PositiveIntegerField(default=1)),
                ('value', models.CharField(max_length=32)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='guestbook.LanguageResponse')),
            ],
        ),
    ]
