# Generated by Django 2.0.2 on 2018-04-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='value',
        ),
    ]
