# Generated by Django 2.0.2 on 2018-04-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_remove_preference_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnote',
            name='note',
            field=models.TextField(max_length=64),
        ),
    ]
