# Generated by Django 2.0.2 on 2018-04-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0006_auto_20180406_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnote',
            name='person',
        ),
        migrations.AddField(
            model_name='personnote',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guestbook.PersonSnapshot'),
        ),
        migrations.AlterField(
            model_name='personnote',
            name='note',
            field=models.TextField(max_length=128),
        ),
    ]
