# Generated by Django 2.0.2 on 2018-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0007_auto_20180406_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsurvey',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
