# Generated by Django 2.0.2 on 2018-04-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0008_personsurvey_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isConstrained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='unitsAvailable',
            field=models.IntegerField(default=0),
        ),
    ]
